# Generated by Django 5.1 on 2024-08-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
