name: Build and deploy Python app to Azure Web App - RopuApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt
          
        # Add environment variables here
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }} 
          
      - name: Collect Static Files
        run: |
          source venv/bin/activate
          python manage.py collectstatic --noinput

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip ./* -x "venv/*" "*.git*" "*.github*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_06F800618C2348CD98200C6750ACA16D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D8A5A1F5FABD4974B2C3AA08D0B52E61 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_70497C7B6D0F4C0B8E80AAFDF6AD75FE }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'RopuApp'
          slot-name: 'Production'
